stages:
  - compile
  - test
  - build

cache:
  paths:
    - ./$CI_PIPELINE_ID

before_script:
  - pwd
  - echo $CI_PIPELINE_ID
  - source activate ./$CI_PIPELINE_ID

configure_env:
  stage: .pre
  image: registry.orr.noaa.gov/erd/centos-conda/centos7-python3.8
  before_script:
    - echo '' # manual override of before_script because we're on runner 12.3 and inherit options are only 12.9+
  script:
    - conda create --prefix ./$CI_PIPELINE_ID
  tags:
    - docker
  artifacts:
    expire_in: 5 days
    paths:
      - ./$CI_PIPELINE_ID

compile_pygnome:
  stage: compile
  only:
    - develop
    - master
    - production
  image: registry.orr.noaa.gov/erd/centos-conda/centos7-python3.8
  script:
    - echo "compiling python3_compile"
    - yum install gcc gcc-c++ make -y
#    - yum install netcdf-devel -y
    - yum install libXext libSM libXrender -y
    - conda install --file conda_requirements.txt
    - pip install git+https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oil_database.git@production#subdirectory=adios_db
    - cd ./py_gnome
    - python setup.py install
#    - python -m pip install ./  # not set up for a pip build :-(
    - cd ../  # make sure that it won't find the source gnome package.
    - python -c "import gnome"
    - cd py_gnome/documentation && make html
  tags:
    - docker
  artifacts:
    when: always
    expire_in: 5 days
    paths:
      - ./$CI_PIPELINE_ID
      - ./py_gnome/documentation/build/html

test_pygnome_develop:
  stage: test
  allow_failure: true
  image: registry.orr.noaa.gov/erd/centos-conda/centos7-python3.8
  only:
    - develop
  script:
    - cd ./py_gnome/tests/unit_tests && pytest --runslow
  tags:
    - docker

test_pygnome_master:
  stage: test
  allow_failure: false
  image: registry.orr.noaa.gov/erd/centos-conda/centos7-python3.8
  only:
    - master
    - production
  script:
    - cd ./py_gnome/tests/unit_tests && pytest --runslow
  tags:
    - docker

develop:
  stage: build
  before_script:
    - echo '' # manual override of before_script because we're on runner 12.3 and inherit options are only 12.9+
  script:
    # get the adios_db code, so we can install it in the docker image
    - git clone --depth 1 -b develop https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oil_database.git
    - docker build -f dockerfile-docs ./py_gnome/documentation/build/html -t registry.orr.noaa.gov/gnome/pygnome/docs
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.orr.noaa.gov/gnome/pygnome/docs

    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker pull registry.orr.noaa.gov/gnome/oillibrary:develop
    # - docker tag registry.orr.noaa.gov/gnome/oillibrary:develop oillibrary

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t registry.orr.noaa.gov/gnome/pygnome:develop
    - docker push registry.orr.noaa.gov/gnome/pygnome:develop
  only:
    - develop
  tags:
    - shell
    - build

master:
  stage: build
  before_script:
    - echo ''
  script:
    # now only building the py_gnome docs with develop
#    - docker build -f dockerfile-docs ./py_gnome/documentation/build/html -t registry.orr.noaa.gov/gnome/pygnome/docs
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker push registry.orr.noaa.gov/gnome/pygnome/docs
    # get the adios_db code, so we can install it in the docker image
    - git clone --depth 1 -b develop https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oil_database.git

    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker pull registry.orr.noaa.gov/gnome/oillibrary:master
    # - docker tag registry.orr.noaa.gov/gnome/oillibrary:master oillibrary

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t registry.orr.noaa.gov/gnome/pygnome:master
    - docker push registry.orr.noaa.gov/gnome/pygnome:master
  only:
     - master
  tags:
     - shell
     - build

production:
  before_script:
    - echo ''
  stage: build
  script:
    # building docs only in develop branch
#    - docker build -f dockerfile-docs ./py_gnome/documentation/build/html -t registry.orr.noaa.gov/gnome/pygnome/docs
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker push registry.orr.noaa.gov/gnome/pygnome/docs

    # get the adios_db code, so we can install it in the docker image
    - git clone --depth 1 -b develop https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oil_database.git

    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # - docker pull registry.orr.noaa.gov/gnome/oillibrary:production
    # - docker tag registry.orr.noaa.gov/gnome/oillibrary:production oillibrary

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t registry.orr.noaa.gov/gnome/pygnome:production
    - docker push registry.orr.noaa.gov/gnome/pygnome:production
  only:
     - production
  tags:
     - shell
     - build
