stages:
  - test
  - build

test:
  stage: test
  image: gitlab.orr.noaa.gov:5002/oillibrary:latest
  script:
  - yum update -y
  - yum install gcc gcc-c++ -y
  - yum install netcdf-devel -y # needed by the C++ code -- it can't find the conda versions
  - yum install libXext libSM libXrender -y  # needed by matplotlib on CentOS

  # make sure the conda channels are set up right
  # the last channel you add will be first on the list
  - conda config --add channels defaults
  - conda config --add channels NOAA-ORR-ERD
  - conda config --add channels conda-forge

  # install the requirements
  - conda install --file conda_requirements.txt

  - cd ./py_gnome
  - python ./setup.py install
  - py.test
  
  tags:
    - docker

develop:
  stage: build
  script:
    - docker pull gitlab.orr.noaa.gov:5002/oillibrary
    - docker tag gitlab.orr.noaa.gov:5002/oillibrary oillibrary
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/pygnome:develop
    - docker push gitlab.orr.noaa.gov:5002/pygnome:develop
  only:
    - develop
  tags:
    - shell
    - build

master:
  stage: build
  script:
    - docker pull gitlab.orr.noaa.gov:5002/oillibrary
    - docker tag gitlab.orr.noaa.gov:5002/oillibrary oillibrary
    - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/pygnome
    - docker push gitlab.orr.noaa.gov:5002/pygnome
  only:
     - master
  tags:
     - shell
     - build
  
production:
  stage: build
  script:
      - docker pull gitlab.orr.noaa.gov:5002/oillibrary:production
      - docker tag gitlab.orr.noaa.gov:5002/oillibrary:production oillibrary
      - docker build -f dockerfile . -t gitlab.orr.noaa.gov:5002/pygnome:production
      - docker push gitlab.orr.noaa.gov:5002/pygnome:production
  only:
     - production
  tags:
     - shell
     - build
