variables:
  PYTHON_VER: "3.8"

stages:
  - compile
  - test
  - build

cache:
  paths:
    - ./$CI_PIPELINE_ID

before_script:
  - pwd
  - echo $CI_PIPELINE_ID
  - source activate ./$CI_PIPELINE_ID

configure_env:
  stage: .pre
  image: registry.orr.noaa.gov/erd/centos-conda/centos7-python$PYTHON_VER
  before_script:
    - echo '' # manual override of before_script because we're on runner 12.3 and inherit options are only 12.9+
  script:
    - conda create --prefix ./$CI_PIPELINE_ID
  tags:
    - docker
  artifacts:
    expire_in: 5 days
    paths:
      - ./$CI_PIPELINE_ID

compile_pygnome:
  stage: compile
  # only:
  #   - develop
  #   - master
  #   - production
  image: registry.orr.noaa.gov/erd/centos-conda/centos7-python$PYTHON_VER
  script:
    - echo "compiling PyGNOME"
    - yum install gcc gcc-c++ make libXext libSM libXrender -y
    # get the adios_db code: needed for tests and requirements
    - git clone --depth 1 -b develop https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oil_database.git
    - conda install -y python=$PYTHON_VER --file conda_requirements.txt --file oil_database/adios_db/conda_requirements.txt

    - conda list --export --no-pip > deploy_requirements.txt

    # install adios_db
    - pip install oil_database/adios_db/
    # - pip install git+https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oil_database.git@production#subdirectory=adios_db
    # export the conda packages for use in later stages.

    - cd ./py_gnome
    - python setup.py install

    - cd ../  # make sure that it won't find the source gnome package.
    - python -c "import gnome"  # make sure that it imports

    # need extra requirements for the docs
    - conda install -y --file conda_requirements_docs.txt
    - cd py_gnome/documentation && make html  # build the docs
  tags:
    - docker
  artifacts:
    when: always
    expire_in: 15 days
    paths:
      - ./$CI_PIPELINE_ID
      - ./py_gnome/documentation/build/html
      - ./deploy_requirements.txt

test_pygnome_develop:
  stage: test
  allow_failure: true
  image: registry.orr.noaa.gov/erd/centos-conda/centos7-python$PYTHON_VER
  except:
    - master
    - production
  script:
    - conda install -y --file conda_requirements_test.txt
    - cd ./py_gnome/tests/unit_tests && pytest --runslow
  tags:
    - docker

test_pygnome_master:
  stage: test
  allow_failure: false
  image: registry.orr.noaa.gov/erd/centos-conda/centos7-python$PYTHON_VER
  except:
    - develop
  script:
    - conda install -y --file conda_requirements_test.txt
    - cd ./py_gnome/tests/unit_tests && pytest --runslow
  tags:
    - docker

build_develop:
  stage: build
  only:
    - develop
  before_script:
    - echo '' # manual override of before_script because we're on runner 12.3 and inherit options are only 12.9+
  script:
    # get the adios_db code, so we can install it in the docker image
    # - git clone --depth 1 -b develop https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oil_database.git

    # build the docs image
    - docker build -f dockerfile-docs ./py_gnome/documentation/build/html -t registry.orr.noaa.gov/gnome/pygnome/docs
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.orr.noaa.gov/gnome/pygnome/docs

    # build the py_gnome image
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . --build-arg PYTHON_VER=$PYTHON_VER -t registry.orr.noaa.gov/gnome/pygnome:develop
    - docker push registry.orr.noaa.gov/gnome/pygnome:develop
  tags:
    - shell
    - build

master:
  stage: build
  before_script:
    - echo ''
  script:
    # get the adios_db code, so we can install it in the docker image
    - git clone --depth 1 -b production https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oil_database.git

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t registry.orr.noaa.gov/gnome/pygnome:master
    - docker push registry.orr.noaa.gov/gnome/pygnome:master
  only:
     - master
  tags:
     - shell
     - build

production:
  before_script:
    - echo ''
  stage: build
  script:
    # get the adios_db code, so we can install it in the docker image
    - git clone --depth 1 -b production https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.orr.noaa.gov/gnome/oil_database/oil_database.git

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t registry.orr.noaa.gov/gnome/pygnome:production
    - docker push registry.orr.noaa.gov/gnome/pygnome:production
  only:
     - production
  tags:
     - shell
     - build
